### ISSUE TITLE
Use floor plane

### ISSUE THREAD

**Issue by memoakten** [memo/pr_kinect2_tracker#25]
Have an option to transform coordinates by floor plane:
1. Detect floor plane. https://msdn.microsoft.com/en-us/library/windowspreview.kinect.bodyframe.floorclipplane.aspx
2. Send floor plane via OSC (to /floorplane x y z w)
3. Have option in settings.xml to display floorplane or not - display as wireframe grid (ofPlanePrimitive ) with dimensions 10x10 and 10x10 segments (so each square is 1m). NOTE: I can't remember if ofPlanePrimitive takes number of _vertices_ or number of _segments_ as a parameter. Make sure the number of _segments_ matches the dimensions, not number of _vertices_. (i.e. so each square is 1m. i.e. 10 segments, i.e. 11 vertices). Optionally, add these as more parameters in setting.xml. e.g. floorPlaneDimX, floorPlaneDimY, floorPlaneResX, floorPlaneResY).
4. Have option in settings.xml to transform coordinates by floor plane. 
   this is using SDK 1.8, but same principles should apply to SDK 2.0 (though floor plane property is accessed from different namespace. see link above)
   http://gamedev.stackexchange.com/questions/80310/transform-world-space-using-kinect-floorclipplane-to-move-origin-to-floor-while

**Comment by devtronslab** [comment]
What exactly does the w value relate to? For my prerecorded video, the
value seems to be returned at 0.78 mostly. Is it essentially a quaternion?

**Comment by memoakten** [comment]
nope not a quaternion, the x,y,z is the normal of the floor plane. and w is
the distance of the floor plane to the kinect. explained at
https://msdn.microsoft.com/en-us/library/windowspreview.kinect.bodyframe.floorclipplane.aspx

I don't know if w is the distance to the floor plane perpendicular to the
kinect (i.e. in the kinects y axis), or if it's the distance to the floor
plane perpendicular to the floor (i.e. in the world y axis). one to
experiment with. if you hold the kinect at a fixed distance to the floor,
and tilt it, if w changes a lot, it's in kinect y axis, otherwise world y
axis

http://www.memo.tv/
_Memo Akten_
www.memo.tv
@memotv http://www.twitter.com/memotv

**Comment by memoakten** [comment]
this is no longer necessary so I'm closing the issue
