### ISSUE TITLE
handstates are coming as int not string

### ISSUE THREAD

**Issue by memoakten** [memo/pr_kinect2_tracker#5]
see https://github.com/diablodale/dp.kinect2/wiki/Message-based-Data
"thehandstate is a string representing one of the five hand states of: unknown, nottracked, open, closed, lasso"

**Comment by devtronslab** [comment]
Ah okay. That should be a simple fix.

**Comment by devtronslab** [comment]
Handstates should be sent as string now
Commit "Issues resolve #1"
